server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /registration

spring:
  datasource:
    password : 
    url : jdbc:mysql://localhost:3306/registration
    username : 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
