server:
  port : 8087
  servlet:
    context-path: /order

spring:
  datasource:
    password : root
#    url : jdbc:mysql://localhost:3306/customerorder
    url : jdbc:mysql://localhost:3306/registration
    username : root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

